[server]
address = "127.0.0.1:50053"  # HTTP3 Gateway слушает здесь
name = "GatewayService"
log_level = "info"

[auth_service]
address = "http://127.0.0.1:50056"  # Адрес Go-сервиса

[tls]
cert_path = "certs/server.crt" # Путь к сертификату
key_path = "certs/server.key"  # Путь к приватному ключу
